name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
#   registryauthtest:
#     runs-on: ubuntu-latest
#     steps:
#       - 
#         name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
#   dockerbuildnpush:
#     needs: registryauthtest
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v2
        
#       - name: Build and push image
#         env:
#           REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
#           PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
#         run: |
#           git_hash=$(git rev-parse --short "$GITHUB_SHA")
#           echo $PASSWORD | docker login --username $REGISTRY --password-stdin
#           docker build -t $REGISTRY/waterup:$git_hash .
#           echo "Pushing image..."
#           docker push $REGISTRY/waterup:$git_hash
          
  updateargocdgit:
    needs: dockerbuildnpush
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: Clone and Commit and Push
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GTOKEN: ${{ secrets.GTOKEN }}
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git clone https://github.com/hojun121/argocd-example-apps.git
          sed -i 's/waterup:.*/waterup:$git_hash/g' waterup/waterup-deployment.yaml
          git add .
          git config --local user.email "hojun121@gmail.com"
          git config --local user.name "hojun121"
          git commit -m 'Update web image tag'
          git push
