name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
#   registryauthtest:
#     runs-on: ubuntu-latest
#     steps:
#       - 
#         name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
  dockerbuild:
#     needs: registryauthtest
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: Build and push image
        env:
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo $PASSWORD | docker login --username $REGISTRY --password-stdin
          docker build -t $REGISTRY/waterup:$git_hash .
          echo "Pushing image..."
          docker push $REGISTRY/waterup:$git_hash
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - 
#         name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
#       - 
#         name: Build and push
#         uses: docker/build-push-action@v2
#         id: docker_build
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/waterup:${{ env.hash }}
          
#   updateargocdgit:
#     needs: dockerbuild
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v3
#         with:
#           repository: 'https://github.com/hojun121/argocd-example-apps.git'
#       - 
#         name: Check Hash
#         run: echo "${{ env.hash }}"
#       - 
#         name: Run Update README.md File
#         run: |
#           git add .
#           git config --local user.email "email"
#           git config --local user.name "name"
#           git commit -m "Update Image Version"
#           git push
